"""Turning a mandate chain into dispute evidence a bank will actually read.

When a cardholder says "I never authorized that", an agent-initiated payment has
none of the evidence a normal one does: no device fingerprint, no browsing
session, no click. Razorpay's dispute API accepts eleven evidence categories and
they all assume a human was at a keyboard.

The mandate chain is the substitute, and it is a better one. It shows the exact
words the person said, the bounded permission they approved, the basket that was
checked against it, the rule-by-rule verdict, and the signatures binding all of
that to the payment. It is also independently verifiable -- the bank does not
have to take the merchant's word, because the subject's own key signed the
permission and anyone holding the public key can check it.

Fields map onto Razorpay's real contest-dispute schema:

    explanation_letter          the narrative, under the 1,000-character limit
    customer_communication      the instruction and the approval they gave
    access_activity_log         the machine-readable chain, for verification
    proof_of_service            what was actually delivered

Nothing here is generated by a model. Every sentence is assembled from ledger
entries, because evidence that a model wrote is evidence the other side gets to
question.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, ConfigDict

from .chain import EventKind, Ledger
from .crypto import VerifyKey
from .models import Paise

__all__ = ["EvidencePack", "assemble_evidence", "EVIDENCE_LIMIT"]

EVIDENCE_LIMIT = 1_000
"""Razorpay caps the explanation letter at 1,000 characters."""


def _ts(unix: int) -> str:
    return datetime.fromtimestamp(unix, UTC).strftime("%d %b %Y, %H:%M UTC")


def _rupees(paise: Paise) -> str:
    return f"Rs {paise / 100:,.2f}"


class EvidencePack(BaseModel):
    """Assembled evidence, ready to submit to the disputes API."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    payment_id: str | None
    amount_paise: Paise
    session_id: str
    explanation_letter: str
    customer_communication: str
    access_activity_log: dict[str, Any]
    proof_of_service: str
    signatures_verified: bool
    chain_intact: bool
    verification_note: str

    def as_contest_payload(self) -> dict[str, Any]:
        """The shape Razorpay's PATCH /disputes/{id}/contest expects for text fields.

        Document-backed fields take uploaded document ids, which a merchant
        supplies from their own systems. Warrant fills the narrative fields and
        hands over a verifiable log to attach.
        """
        return {
            "amount": self.amount_paise,
            "summary": self.explanation_letter[:EVIDENCE_LIMIT],
            "action": "draft",
        }


def assemble_evidence(
    ledger: Ledger,
    session_id: str,
    *,
    subject_key: VerifyKey,
    payment_id: str | None = None,
) -> EvidencePack:
    """Build an evidence pack for one settled payment from the ledger alone."""
    entries = list(ledger.entries(session_id))
    if not entries:
        raise ValueError(f"no ledger entries for session {session_id}")

    intent_entry = next(e for e in entries if e.kind is EventKind.INTENT_ISSUED)
    intent_env = intent_entry.payload["intent"]
    intent_body = intent_env["body"]
    derivation = intent_entry.payload.get("derivation", {})

    settlements = [e for e in entries if e.kind is EventKind.DEBIT_SETTLED]
    if payment_id:
        settlements = [
            e
            for e in settlements
            if e.payload["receipt"]["body"]["rail"].get("payment_id") == payment_id
        ]
    if not settlements:
        raise ValueError(f"no settled payment found in session {session_id}")

    receipt_env = settlements[-1].payload["receipt"]
    receipt_body = receipt_env["body"]
    amount = receipt_body["amount_paise"]
    rail = receipt_body["rail"]

    cart_entry = next(
        e
        for e in entries
        if e.kind is EventKind.CART_ALLOWED
        and e.payload["cart"]["digest"] == receipt_body["cart_digest"]
    )
    cart_body = cart_entry.payload["cart"]["body"]
    decision = cart_entry.payload["decision"]

    # -- independent verification ---------------------------------------- #

    from .crypto import Signature
    from .models import IntentMandate

    intent = IntentMandate.model_validate(intent_body)
    sig = intent_env.get("signature")
    signatures_ok = bool(
        sig and subject_key.verify(intent.body(), Signature.from_dict(sig))
    )
    chain_ok = ledger.audit() is None

    scope = intent_body["scope"]
    passed = [c["rule"] for c in decision["checks"] if c["status"] == "pass"]

    # -- the narrative ---------------------------------------------------- #

    letter = (
        f"This {_rupees(amount)} payment was initiated by the cardholder's own AI agent "
        f"under a spending permission the cardholder personally authorized on "
        f"{_ts(intent_body['issued_at'])}.\n\n"
        f"The cardholder's instruction was: \"{intent_body['utterance']}\"\n\n"
        f"They approved a permission bounded to {_rupees(scope['max_total_paise'])} total, "
        f"{_rupees(scope['max_per_txn_paise'])} per order, at most {scope['max_txns']} "
        f"orders, restricted to {', '.join(scope['merchants'])}, expiring "
        f"{_ts(scope['expires_at'])}. That permission was signed with the cardholder's "
        f"own device key ({sig['key_id'] if sig else 'unsigned'}).\n\n"
        f"Before this debit, the basket was checked against that permission and passed "
        f"{len(passed)} independent checks. The signed permission, the checked basket and "
        f"this payment are cryptographically bound in the attached activity log, which can "
        f"be verified against the cardholder's public key without relying on our records."
    )
    if len(letter) > EVIDENCE_LIMIT:
        letter = (
            f"This {_rupees(amount)} payment was initiated by the cardholder's own AI agent "
            f"under a permission they personally authorized on "
            f"{_ts(intent_body['issued_at'])}: \"{intent_body['utterance']}\". "
            f"The permission was bounded to {_rupees(scope['max_total_paise'])} at "
            f"{', '.join(scope['merchants'])} and signed with the cardholder's device key. "
            f"The basket passed {len(passed)} checks against it before the debit. The "
            f"attached activity log binds permission, basket and payment cryptographically "
            f"and is independently verifiable."
        )[:EVIDENCE_LIMIT]

    communication = (
        f"Instruction given by the cardholder at {_ts(intent_body['issued_at'])}:\n"
        f'  "{intent_body["utterance"]}"\n\n'
        f"Permission shown to the cardholder for approval before signing:\n"
        f"  \"{derivation.get('plain_english', '(not recorded)')}\"\n\n"
        f"Approved and signed by device key "
        f"{sig['key_id'] if sig else '(unsigned)'}."
    )

    items = "\n".join(
        f"  - {i['name']} x{i['qty']} at {_rupees(i['unit_paise'])}"
        for i in cart_body["line_items"]
    )
    service = (
        f"Order placed with {cart_body['merchant']} for {_rupees(cart_body['total_paise'])}:\n"
        f"{items}\n\n"
        f"Settled {_ts(receipt_body['settled_at'])} as "
        f"{rail.get('payment_id') or rail.get('order_id')}."
    )

    activity_log = {
        "schema": "warrant.mandate_chain.v1",
        "session_id": session_id,
        "verification": {
            "algorithm": "ed25519-sha256-jcs",
            "subject_public_key": subject_key.b64,
            "subject_key_id": subject_key.key_id,
            "instructions": (
                "Canonicalize each body per RFC 8785, verify its signature with the "
                "subject public key, then confirm each digest matches the parent "
                "reference and that ledger entry hashes chain from genesis."
            ),
        },
        "intent_mandate": intent_env,
        "cart_mandate": cart_entry.payload["cart"],
        "debit_receipt": receipt_env,
        "decision": decision,
        "ledger": [
            {
                "seq": e.seq,
                "kind": str(e.kind),
                "recorded_at": e.recorded_at,
                "prev_hash": e.prev_hash,
                "hash": e.hash,
            }
            for e in entries
        ],
    }

    if signatures_ok and chain_ok:
        note = (
            "The cardholder's signature on the permission verifies against their public "
            "key, and the ledger chain recomputes intact from genesis."
        )
    elif not signatures_ok:
        note = "WARNING: the permission signature did not verify. Do not submit this pack."
    else:
        note = "WARNING: the ledger chain is broken. Do not submit this pack."

    return EvidencePack(
        payment_id=rail.get("payment_id"),
        amount_paise=amount,
        session_id=session_id,
        explanation_letter=letter,
        customer_communication=communication,
        access_activity_log=activity_log,
        proof_of_service=service,
        signatures_verified=signatures_ok,
        chain_intact=chain_ok,
        verification_note=note,
    )
